# Generated by Django 2.0.4 on 2018-05-11 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default='78a77ef', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=254)),
                ('middle_name', models.CharField(blank=True, default='', max_length=254)),
                ('last_name', models.CharField(blank=True, default='', max_length=254)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoPasswordWaitingForEmailConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=main.models.gen_token, editable=False, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('browser', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='', max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCookie',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_cookie', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cookie', models.CharField(default='5e2cb20d705b48c98238', editable=False, max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='nopasswordwaitingforemailconfirm',
            name='user',
            field=models.OneToOneField(db_column='user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_confirm', to=settings.AUTH_USER_MODEL),
        ),
    ]
